### ISSUE TITLE
关于MixSNIPS性能问题

### ISSUE THREAD

**Issue by LindgeW** [yizhen20133868/GL-GIN#1]
请问MixSNIPS数据集上的slot filling和overall性能怎么会这么高（有点离谱）？

**Comment by qinlibo-hit** [comment]
@LindgeW ，您好，感谢关注，这是因为MIXSNIPS数据集是由SNIPS数据集简单构造而来，SNIPS数据集本身已经有模型刷到99%以上的intent和slot相关值，所以造成mixsnips偏高，构造一个更有挑战的多意图数据集仍然是一个重要的研究课题。谢谢

**Comment by LindgeW** [comment]
你好，save/param.json 是最佳参数设置吗？word_embedding_dim都是32?
