### ISSUE TITLE
想确认一下数据  

### ISSUE THREAD

**Issue by jingyonglin** [yizhen20133868/GL-GIN#2]
作者您好,
请问repository里的data  mixATIS_clean 和mixSNIPS_clean 和其分割文件就是paper里result对应使用的数据是么?

**Comment by jingyonglin** [comment]
在 paper 中4.1 Datasets 里 '756 utterances for validation' 但是我统计的是759

**Comment by qinlibo-hit** [comment]
@jingyonglin ，您好，是的，感谢指出，这是我们的typo，是759。我们会在arxiv版本进行修正。祝好。
