### ISSUE TITLE
关于中文意图识别与槽位填充的问题，slot值在原文未出现该如何标注

### ISSUE THREAD

**Issue by RayShark** [yizhen20133868/GL-GIN#3]
您好，我看了你们的文章，并且也运行了代码，基本上复现了论文中的结果，非常感谢你们能够开源这项工作！
我目前希望利用这套代码处理中文的意图识别和槽位填充的问题，但还是有些地方不太明白想咨询一下：

我目前为了方便直接模拟英文的数据集，将中文按照字级别拆开，即['订', '机', '票']这样的结构，效果不是很理想。

所以想问一下，按照这套代码逻辑更适合下面哪一种分词呢：

- 字级别分词
- jieba分词
- 套用Bert的词向量

还有一个问题困扰了我很久，**就是如果slot在原文中没有对应的word，该如何去做标注**呢？
比如：

- text：自驾游去北京都经过那些地方啊？
- slots：{'目的地': '北京', '询问类型': '导航'}
- intent：旅游咨询

这里槽位值“导航”就没法在text里标注。。。

**Comment by qinlibo-hit** [comment]
@RayShark 您好，感谢关注我们的工作，中文已经超过了我们这篇工作范畴，我们是英文为主，推荐一篇中文SLU工作，希望能帮到你。Injecting Word Information with Multi-Level Word Adapter for Chinese Spoken Language Understanding ICASSP2021.

**Comment by RayShark** [comment]
嗯嗯，感谢您的分享，MLWA确实给了我很多思路~
