### ISSUE TITLE
关于论文中metrics的问题

### ISSUE THREAD

**Issue by jingyonglin** [yizhen20133868/GL-GIN#4]
作者您好,
我这边按照readme做好了需求环境,
尝试了用您在repo中留的titan xp对应训练参数, 在tesla v100 上进行训练
并没有复现出论文的结果, 在 mixSNIPS clean 和 mixATIS clean上均无法接近论文的效果, 具体训练log我贴在附件内
[mix_Atis.txt](https://github.com/yizhen20133868/GL-GIN/files/7029628/mix_Atis.txt)
[mix_snips.txt](https://github.com/yizhen20133868/GL-GIN/files/7029629/mix_snips.txt)

请问是有其他细节么，我想复现论文内sota的结果,最起码能接近[](url)

**Comment by qinlibo-hit** [comment]
@jingyonglin 您好，感谢关注我们的工作，细节在论文已经呈现完，并且也有不少老师同学复现了结果。由于不同平台，建议可以调一下参数，比如dropout，batch_size, 等参数，应该是不难复现结果的，祝好。

**Comment by jingyonglin** [comment]
@yizhen20133868 您好, 我自己尝试了几组的batch size和dropout rate, 仍然不理想
我确实是想进行sota的复现, 平台不同但是在相同参数下,还是很有机会实现的, 可以给出更多信息么, 比如cuda manual seed; random seed

**Comment by qinlibo-hit** [comment]
@jingyonglin 您好，我们查了一下，对于MixATIS数据集，我们尝试过的超参数设置包括：word_embedding_dim:[64, 128]; intent_embedding_dim[64, 128]; decoder_gat_hidden_dim[64, 128]，slot_graph_window[2, 3, 4]
对于MixSNIPS数据集，我们主要尝试的超参数设置为：word_embedding_dim:[64, 128]; intent_embedding_dim[64, 128]; decoder_gat_hidden_dim[64, 128]，slot_graph_window[1]
两个数据集对于seed没有进行过调整。建议您那边也可以对一些参数进行grid search多调一些。谢谢。

**Comment by jingyonglin** [comment]
> @jingyonglin 您好，我们查了一下，对于MixATIS数据集，我们尝试过的超参数设置包括：word_embedding_dim:[64, 128]; intent_embedding_dim[64, 128]; decoder_gat_hidden_dim[64, 128]，slot_graph_window[2, 3, 4]
> 对于MixSNIPS数据集，我们主要尝试的超参数设置为：word_embedding_dim:[64, 128]; intent_embedding_dim[64, 128]; decoder_gat_hidden_dim[64, 128]，slot_graph_window[1]
> 两个数据集对于seed没有进行过调整。建议您那边也可以对一些参数进行grid search多调一些。谢谢。

okk, 我会根据这些参数继续试验, 谢谢回复
