### ISSUE TITLE
mixatis数据atis_day_name类别在train中未出现

### ISSUE THREAD

**Issue by adzhua** [yizhen20133868/GL-GIN#6]
你好，我发现mixatis数据集test中出现了atis_day_name意图类别，但在train中未出现，这个是数据的原因吗？在论文中怎么处理的？

**Comment by qinlibo-hit** [comment]
@adzhua 您好，感谢对我们工作感兴趣。是的，这个是数据的原因，原来的ATIS就会出现这样的问题，但是所有的baseline都是公平比较，所以没有关系，在我们模型中我们没有额外处理。应该所有模型都预测不对。祝好。
