### ISSUE TITLE
More information about t_test

### ISSUE THREAD

**Issue by waterwaterrr** [yizhen20133868/GL-GIN#7]
Why we can't re-produce the score in the paper by using the recommended hyper-parameters? Besides, i am curious about the t-test, as far as i know, t-test need more than one-time exp. Although we acheived the exactly same performance by using the previded "best model", We can't pass t-test by using the recommended  hyper-parameters.  Could you please provide more best-model by differents hyper-parameters or provide more details about training.

**Comment by qinlibo-hit** [comment]
@waterwaterrr Thank you very much for your interests to our work. To facilitate the research, we choose one of the results and  provide the GPU model and the Pytorch version to help other to quickly reproduce our results. Specifically, we conducted the MixATIS experiments on RTX 2080TI and MixSNIPS experiments on TITAN Xp. If you have any other questions, please hesitate to concat me (yizhen-nlp (wechat) or lbqin@ir.hit.edu.cn (email)).
